"""Generate sales report showing total melons each salesperson sold."""

# Create empty lists where we can add salespeople and melons_sold as we iterate
through data.
salespeople = []
melons_sold = []

# File (f) is generated by sales report
f = open('sales-report.txt')

# Iterates through file by line striping whitespace and spliting at vertical bars
for line in f:
    line = line.rstrip()
    entries = line.split('|')

    # Create variables to represent salesperson name and number of melons sold
    salesperson = entries[0]
    melons = int(entries[2])

    # If salesperson already exists, find the index of that sales person
    # And add new melons sold onto their existing sales
    if salesperson in salespeople:
        position = salespeople.index(salesperson)

        melons_sold[position] += melons

    # Add new salespersons to sales people, add new melons sold to melons_sold
    # On two separate lists
    else:
        salespeople.append(salesperson)
        melons_sold.append(melons)

# Iterate through salespeople to map list indices with melon indices.
# Print string describing sales by salesperson.
for i in range(len(salespeople)):
    print(f'{salespeople[i]} sold {melons_sold[i]} melons')
